//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msts.Topics.Chapter06___Globalization_and_Accessibility.Lesson02___Accessibility
{


    public partial class GeneralAccessibilityRules
    {
    }
}
