<%@ Page Title="" Language="C#" MasterPageFile="~/Topics/Chapter02 - Master - themes - caching/Lesson01 - MasterPages/ClassicMaster.Master" AutoEventWireup="true" CodeBehind="WorkingWithTheEntityDataSourceControl.aspx.cs" Inherits="Msts.Topics.Chapter12___Data_binding.Lesson01___DataSource.WorkingWithTheEntityDataSourceControl" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>
        EntityDataSource control
    </h1>
    <asp:UpdatePanel runat="server" ID="updatePanel">
        <ContentTemplate>
            <div>
                <asp:Label Text="Description filter" runat="server" ID="descriptionFilterLabel" AssociatedControlID="descriptionFilter" />
            </div>
            <div>
                <asp:TextBox runat="server" ID="descriptionFilter" />
            </div>
            <div>
                <asp:Label Text="Minimum value" runat="server" ID="minimumFilterLabel" AssociatedControlID="minimumFilter" />
            </div>
            <div>
                <asp:DropDownList runat="server" ID="minimumFilter">
                    <asp:ListItem Text="Select an item..." Value="" Selected="True" />
                    <asp:ListItem Text="50" />
                    <asp:ListItem Text="100" />
                    <asp:ListItem Text="150" />
                    <asp:ListItem Text="200" />
                </asp:DropDownList>
            </div>
            <div>
                <asp:Label Text="Maximum filter" runat="server" ID="maximumFilterLabel" AssociatedControlID="maximumFilter" />
            </div>
            <div>
                <asp:RadioButtonList runat="server" ID="maximumFilter">
                    <asp:ListItem Text="50" />
                    <asp:ListItem Text="100" />
                    <asp:ListItem Text="150" />
                    <asp:ListItem Text="200" />
                    <asp:ListItem Text="250" Selected="True" />
                </asp:RadioButtonList>
            </div>
            <div>
                <asp:Button Text="Apply filter" runat="server" ID="applyFilter" OnClick="applyFilter_Click" />
            </div>
            <div>
                <asp:Button Text="Reset Filter" runat="server" ID="resetFilter" OnClick="resetFilter_Click" />
            </div>
            <asp:UpdateProgress ID="UpdateProgress1" runat="server">
                <ProgressTemplate>
                    Processing...
                </ProgressTemplate>
            </asp:UpdateProgress>
            <asp:EntityDataSource runat="server" ID="eds"
                ConnectionString="<%$ ConnectionStrings: PubsEntities %>"
                DefaultContainerName="PubsEntities"
                EntitySetName="jobs"
                AutoPage="true"
                AutoSort="true"
                EnableUpdate="true"
                EnableDelete="true"
                EnableFlattening="true"
                OnQueryCreated="eds_QueryCreated"
                OnContextCreating="eds_ContextCreating"
                Where="it.max_lvl <= @maximumLevel and it.min_lvl >= @minimumLevel">
                <WhereParameters>
                    <asp:ControlParameter 
                        ConvertEmptyStringToNull="true"
                        DefaultValue="0"
                        ControlID="minimumFilter" 
                        Type="Byte" 
                        Name="minimumLevel" 
                        PropertyName="SelectedValue" />
                    <asp:ControlParameter 
                        ConvertEmptyStringToNull="true"
                        ControlID="maximumFilter" 
                        Type="Byte"  
                        Name="maximumLevel" 
                        PropertyName="SelectedValue"/>
                </WhereParameters>
            </asp:EntityDataSource>
            <asp:GridView runat="server" ID="gv"
                DataSourceID="eds" DataKeyNames="job_id"
                AllowPaging="true" AllowSorting="true" PageSize="5"
                AutoGenerateColumns="true" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateSelectButton="true">
                <SelectedRowStyle Font-Bold="true" />
            </asp:GridView>
            <asp:EntityDataSource runat="server" ID="eds2"
                ContextTypeName="Msts.DataAccess.EFData.PubsEntities"
                EntitySetName="jobs"
                EnableFlattening="true"
                Where="it.job_id == @job_id"
                AutoPage="false" AutoSort="true"
                OnContextCreating="eds_ContextCreating"
                EnableDelete="true" EnableInsert="true" EnableUpdate="true">
                <WhereParameters>
                    <asp:ControlParameter 
                        ControlID="gv"
                        ConvertEmptyStringToNull="true"
                        Direction="Input"
                        Name="job_id"
                        PropertyName="SelectedValue"
                        Type="Int16" />
                </WhereParameters>
            </asp:EntityDataSource>
            <asp:DetailsView runat="server" ID="dv"
                DataSourceID="eds2" DataKeyNames="job_id"
                AutoGenerateRows="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateInsertButton="true"
                OnItemInserted="dv_ItemInserted" OnItemDeleted="dv_ItemDeleted" OnItemUpdated="dv_ItemUpdated">
                <Fields>
                    <asp:BoundField DataField="job_id" ReadOnly="true" InsertVisible="false" HeaderText="ID" />
                    <asp:BoundField DataField="job_desc" HeaderText="Description" />
                    <asp:BoundField DataField="min_lvl" HeaderText="Minimum level" />
                    <asp:BoundField DataField="max_lvl" HeaderText="Maximum level" />
                </Fields>
            </asp:DetailsView>
        </ContentTemplate>
        <Triggers>
            <asp:AsyncPostBackTrigger ControlID="resetFilter" />
            <asp:AsyncPostBackTrigger ControlID="applyFilter" />
        </Triggers>
    </asp:UpdatePanel>
</asp:Content>
