<%@ Page Title="" Language="C#" MasterPageFile="~/Topics/Chapter02 - Master - themes - caching/Lesson01 - MasterPages/ClassicMaster.Master" AutoEventWireup="true" CodeBehind="WorkingWithTheLinqDataSourceControl.aspx.cs" Inherits="Msts.Topics.Chapter12___Data_binding.Lesson01___DataSource.WorkingWithTheLinqDataSourceControl" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>
        LinqDataSource control
    </h1>
    <asp:UpdatePanel runat="server" ID="mainUpdatePanel">
        <ContentTemplate>
            <div>
                Description filter:
                <asp:TextBox runat="server" ID="descriptionFilter" />
            </div>
            <div>
                Minimum level: 
                <asp:DropDownList runat="server" ID="minimumFilter">
                    <asp:ListItem Text="Please select a value..." Value="" Selected="True" />
                    <asp:ListItem Text="50" />
                    <asp:ListItem Text="100" />
                    <asp:ListItem Text="150" />
                    <asp:ListItem Text="200" />
                    <asp:ListItem Text="250" />
                </asp:DropDownList>
            </div>
            <div>
                Maximum filter:
                <asp:RadioButtonList runat="server" ID="maximumFilter">
                    <asp:ListItem Text="50" />
                    <asp:ListItem Text="100" />
                    <asp:ListItem Text="150" />
                    <asp:ListItem Text="200" />
                    <asp:ListItem Text="250" Selected="True" />
                </asp:RadioButtonList>
            </div>
            <div>
                <asp:Button Text="Apply filter..." runat="server" ID="applyFilter" OnClick="applyFilter_Click" />
            </div>
            <div>
                <asp:Button Text="Reset Filter..." runat="server" ID="resetFilter" OnClick="resetFilter_Click" />
            </div>
            <asp:UpdateProgress runat="server" ID="mainUpdateProgress" DisplayAfter="0">
                <ProgressTemplate>
                    Processing...
                </ProgressTemplate>
            </asp:UpdateProgress>
            <asp:LinqDataSource runat="server" ID="lds"
                OnContextCreating="lds_ContextCreating"
                ContextTypeName="Msts.DataAccess.PubsDataContext"
                TableName="jobs"
                EnableDelete="true" EnableInsert="false" EnableUpdate="true"
                Where="it.min_lvl >= @min_lvl and it.max_lvl <= @max_lvl"
                OnQueryCreated="lds_QueryCreated">
                <WhereParameters>
                    <asp:ControlParameter
                        ConvertEmptyStringToNull="true"
                        ControlID="descriptionFilter"
                        Direction="Input"
                        Name="job_desc"
                        PropertyName="Text"
                        Type="String" />
                    <asp:ControlParameter 
                        ControlID="minimumFilter"
                        ConvertEmptyStringToNull="true"
                        DefaultValue="0"
                        Direction="Input"
                        Name="min_lvl"
                        PropertyName="SelectedValue"
                        Type="Byte" />
                    <asp:ControlParameter
                        ControlID="maximumFilter"
                        ConvertEmptyStringToNull="true"
                        Direction="Input"
                        Name="max_lvl"
                        PropertyName="SelectedValue"
                        Type="Byte" />
                </WhereParameters>
            </asp:LinqDataSource>
            <asp:GridView runat="server" ID="gv"
                DataSourceID="lds" DataKeyNames="job_id"
                EnablePersistedSelection="true"
                AllowPaging="true" PageSize="5" AllowSorting="true"
                AutoGenerateColumns="true"
                AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateSelectButton="true">
                <SelectedRowStyle Font-Bold="true" />
            </asp:GridView>
            <asp:LinqDataSource runat="server" ID="lds2"
                ContextTypeName="Msts.DataAccess.PubsDataContext"
                TableName="jobs"
                AutoPage="false" AutoSort="false"
                EnableDelete="true" EnableInsert="true" EnableUpdate="true"
                AutoGenerateWhereClause="true"
                OnDeleted="lds2_Deleted"
                OnInserted="lds2_Inserted"
                OnUpdated="lds2_Updated">
                <WhereParameters>
                    <asp:ControlParameter
                        ControlID="gv"
                        DefaultValue="-1"
                        ConvertEmptyStringToNull="true"
                        Direction="Input"
                        Name="job_id"
                        PropertyName="SelectedValue"
                        Type="Int16" />
                </WhereParameters>
            </asp:LinqDataSource>
            <asp:DetailsView runat="server" ID="dv"
                DataSourceID="lds2" DataKeyNames="job_id"
                AllowPaging="false"
                AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateInsertButton="true"
                AutoGenerateRows="false">
                <Fields>
                    <asp:BoundField DataField="job_id" HeaderText="ID" ReadOnly="true" InsertVisible="false" />
                    <asp:BoundField DataField="job_desc" HeaderText="Description" />
                    <asp:BoundField DataField="min_lvl" HeaderText="Minimum" />
                    <asp:BoundField DataField="max_lvl" HeaderText="Maximum" />
                </Fields>
            </asp:DetailsView>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
