<%@ Page Title="" Language="C#" MasterPageFile="~/Topics/Chapter02 - Master - themes - caching/Lesson01 - MasterPages/ClassicMaster.Master" AutoEventWireup="true" CodeBehind="WorkingWithTheObjectDataSourceControl.aspx.cs" Inherits="Msts.Topics.Chapter12___Data_binding.Lesson01___DataSource.WorkingWithTheObjectDataSourceControl" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>
        ObjectDataSource control
    </h1>

    <asp:UpdatePanel runat="server" ID="updatePanel">
        <Triggers>
            <asp:AsyncPostBackTrigger ControlID="applyFilter" />
        </Triggers>
        <ContentTemplate>
            <div>
                Job description filter:
                <asp:TextBox runat="server" ID="descriptionFilter" />
            </div>
            <div>
                Minimum level filter:
                <asp:DropDownList runat="server" ID="minimumFilter" AppendDataBoundItems="true">
                    <asp:ListItem Text="Select a value" Value="" Selected="True" />
                    <asp:ListItem Text="50" />
                    <asp:ListItem Text="100" />
                    <asp:ListItem Text="150" />
                    <asp:ListItem Text="200" />
                </asp:DropDownList>
            </div>
            <div>
                Maximum level filter:
                <asp:RadioButtonList runat="server" ID="maximumFilter">
                    <asp:ListItem Text="50" />
                    <asp:ListItem Text="100" />
                    <asp:ListItem Text="150" />
                    <asp:ListItem Text="200" />
                    <asp:ListItem Text="250" Selected="True" />
                </asp:RadioButtonList>
            </div>
            <asp:UpdateProgress ID="UpdateProgress1" runat="server">
                <ProgressTemplate>
                    Processing...
                </ProgressTemplate>
            </asp:UpdateProgress>
            <div>
                <asp:Button Text="Apply filter" runat="server" ID="applyFilter" OnClick="applyFilter_Click" />
            </div>
            <div>
                <asp:Button Text="Reset filter" runat="server" ID="resetFilter" OnClick="resetFilter_Click" />
            </div>
            <asp:ObjectDataSource runat="server" ID="ods"
                TypeName="Msts.Topics.Chapter12___Data_binding.Lesson01___DataSource.ObjectDataSourceProvider"
                DataObjectTypeName="Msts.Topics.Chapter12___Data_binding.Lesson01___DataSource.JobDTO"
                SelectMethod="GetJobs"
                SelectCountMethod="GetJobsCount"
                MaximumRowsParameterName="pageSize"
                StartRowIndexParameterName="rowIndex"
                SortParameterName="sortCriteria"
                EnablePaging="true"
                UpdateMethod="UpdateJob"
                DeleteMethod="DeleteJob">
                <SelectParameters>
                    <asp:ControlParameter 
                        ControlID="descriptionFilter" 
                        Type="String" 
                        ConvertEmptyStringToNull="true" 
                        Direction="Input" 
                        PropertyName="Text" 
                        Name="description" />
                    <asp:ControlParameter 
                        ControlID="minimumFilter"
                        Type="Byte"
                        ConvertEmptyStringToNull="true"
                        PropertyName="SelectedValue"
                        Name="minimum"/>
                    <asp:ControlParameter 
                        ControlID="maximumFilter"
                        Type="Byte"
                        ConvertEmptyStringToNull="true"
                        Name="maximum"/>
                </SelectParameters>
            </asp:ObjectDataSource>
            <asp:GridView runat="server" ID="gv" DataSourceID="ods" DataKeyNames="ID"
                AllowPaging="true" PageSize="5" AllowSorting="true" EnablePersistedSelection="true"
                AutoGenerateColumns="true"
                AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateSelectButton="true"
                OnPageIndexChanged="gv_PageIndexChanged">
                <SelectedRowStyle Font-Bold="true" />
            </asp:GridView>
            <hr />
            <asp:ObjectDataSource runat="server" ID="jobODS"
                TypeName="Msts.Topics.Chapter12___Data_binding.Lesson01___DataSource.ObjectDataSourceProvider"
                DataObjectTypeName="Msts.Topics.Chapter12___Data_binding.Lesson01___DataSource.JobDTO"
                SelectMethod="GetJob"
                EnablePaging="false"
                InsertMethod="AddJob"
                UpdateMethod="UpdateJob"
                DeleteMethod="DeleteJob">
                <SelectParameters>
                    <asp:ControlParameter 
                        ControlID="gv"
                        Type="Int16"
                        Name="jobID"
                        PropertyName="SelectedValue"/>
                </SelectParameters>
            </asp:ObjectDataSource>
            <asp:Panel runat="server" GroupingText="Details">
                <asp:DetailsView runat="server" ID="jobDetails" DataSourceID="jobODS" DataKeyNames="ID"
                    AutoGenerateEditButton="true"
                    AutoGenerateDeleteButton="true"
                    AllowPaging="false"
                    AutoGenerateRows="false"
                    AutoGenerateInsertButton="true"
                    OnItemUpdated="jobDetails_ItemUpdated"
                    OnItemInserted="jobDetails_ItemInserted"
                    OnItemDeleted="jobDetails_ItemDeleted">
                    <Fields>
                        <asp:BoundField DataField="ID" ReadOnly="true" HeaderText="ID" InsertVisible="false" />
                        <asp:BoundField DataField="Description" HeaderText="Job Description" />
                        <asp:BoundField DataField="Minimum" HeaderText="Minimum level" />
                        <asp:BoundField DataField="Maximum" HeaderText="Maximum level" />
                    </Fields>
                </asp:DetailsView>
            </asp:Panel>
            </div>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
