<%@ Page Title="" Language="C#" MasterPageFile="~/Topics/Chapter02/Lesson01 - MasterPages/ClassicMaster.Master" AutoEventWireup="true" CodeBehind="WorkingWithTheGridViewControl.aspx.cs" Inherits="Msts.Topics.Chapter12___Data_binding.Lesson02___DataBound.WorkingWithTheGridViewControl" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>
        Working with the GridView control
    </h1>
    <script>
        function pageLoad () {
            var $grid = $("table[id$=myCustomGridView]");
            var $rows = $("> tbody > tr:not(:has(th))", $grid);
            var $master = $("input:checkbox[id$=masterCheck]");
            var $gridChecks = $("input:checkbox", $rows);

            $master.change(function (e) {
                e.preventDefault();

                $gridChecks.prop("checked", $master.is(":checked"));
            });

            $gridChecks.change(function (e) {
                e.preventDefault();

                var masterValue = true;

                for (var i = 0; i < $gridChecks.length; i++) {
                    var $x = $gridChecks.eq(i);

                    if (!$x.is(":checked")) {
                        masterValue = false;
                        break;
                    }
                }

                $master.prop("checked", masterValue);
            });
        };
    </script>
    <asp:CheckBox Text="Check/Uncheck all" runat="server" ID="masterCheck" />
    <asp:UpdatePanel runat="server">
        <ContentTemplate>
            <asp:UpdateProgress runat="server" DisplayAfter="0">
                <ProgressTemplate>
                    Processing...
                </ProgressTemplate>
            </asp:UpdateProgress>
            <asp:EntityDataSource runat="server" ID="eds"
                ContextTypeName="Msts.DataAccess.EFData.PubsEntities"
                OnContextCreating="eds_ContextCreating"
                EntitySetName="jobs"
                Include="employees"
                AutoPage="true" AutoSort="true"
                EnableDelete="true" EnableInsert="true" EnableUpdate="true"
                EnableFlattening="false">

            </asp:EntityDataSource>
            <asp:EntityDataSource runat="server" ID="eds2"
                ContextTypeName="Msts.DataAccess.EFData.PubsEntities"
                OnContextCreating="eds_ContextCreating"
                EntitySetName="employees">

            </asp:EntityDataSource>
            <asp:GridView runat="server" ID="myCustomGridView"
                DataSourceID="eds"
                DataKeyNames="job_id"
                AllowPaging="true" AllowSorting="true" PageSize="5"
                AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateSelectButton="true" CellPadding="4" ForeColor="#333333" GridLines="None"
                OnRowDataBound="myCustomGridView_RowDataBound"
                OnRowUpdating="myCustomGridView_RowUpdating">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775"></AlternatingRowStyle>
                <Columns>
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:CheckBox runat="server" ID="myCheckBox" Text='<%# Eval("job_desc") %>' />
                        </ItemTemplate>
                        <EditItemTemplate>

                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Employees">
                        <ItemTemplate>
                            <asp:GridView runat="server" ID="employeesGrid"
                                DataSource='<%# DataBinder.Eval(Container.DataItem, "employees") %>'
                                DataKeyNames="emp_id"
                                ShowHeader="false"
                                AutoGenerateColumns="false" CellPadding="4" ForeColor="#333333" GridLines="None">
                                <AlternatingRowStyle BackColor="White"></AlternatingRowStyle>
                                <Columns>
                                    <asp:TemplateField ShowHeader="false">
                                        <ItemTemplate>
                                            <div>
                                                <asp:Label Text='<%# Eval("fname") %>' runat="server" />
                                                <asp:Label Text='<%# Eval("lname") %>' runat="server" />
                                            </div>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                </Columns>
                                <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White"></FooterStyle>

                                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White"></HeaderStyle>

                                <PagerStyle HorizontalAlign="Center" BackColor="#FFCC66" ForeColor="#333333"></PagerStyle>

                                <RowStyle BackColor="#FFFBD6" ForeColor="#333333"></RowStyle>

                                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy"></SelectedRowStyle>

                                <SortedAscendingCellStyle BackColor="#FDF5AC"></SortedAscendingCellStyle>

                                <SortedAscendingHeaderStyle BackColor="#4D0000"></SortedAscendingHeaderStyle>

                                <SortedDescendingCellStyle BackColor="#FCF6C0"></SortedDescendingCellStyle>

                                <SortedDescendingHeaderStyle BackColor="#820000"></SortedDescendingHeaderStyle>
                            </asp:GridView>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:CheckBoxList runat="server" ID="employeesList"
                                DataSourceID="eds2"
                                RepeatColumns="3" RepeatDirection="Horizontal" RepeatLayout="Table"
                                DataTextField="fname"
                                DataValueField="emp_id">
                            </asp:CheckBoxList>
                        </EditItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle BackColor="#999999"></EditRowStyle>

                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White"></FooterStyle>

                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White"></HeaderStyle>

                <PagerStyle HorizontalAlign="Center" BackColor="#284775" ForeColor="White"></PagerStyle>

                <RowStyle BackColor="#F7F6F3" ForeColor="#333333"></RowStyle>

                <SelectedRowStyle Font-Bold="true" BackColor="#E2DED6" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2"></SortedAscendingCellStyle>

                <SortedAscendingHeaderStyle BackColor="#506C8C"></SortedAscendingHeaderStyle>

                <SortedDescendingCellStyle BackColor="#FFFDF8"></SortedDescendingCellStyle>

                <SortedDescendingHeaderStyle BackColor="#6F8DAE"></SortedDescendingHeaderStyle>
            </asp:GridView>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
