<%@ Page Title="" Language="C#" MasterPageFile="~/Topics/Chapter02/Lesson01 - MasterPages/ClassicMaster.Master" AutoEventWireup="true" CodeBehind="WorkingWithTheDetailsViewControl.aspx.cs" Inherits="Msts.Topics.Chapter12___Data_binding.Lesson02___DataBound.WorkingWithTheDetailsViewControl" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>
        DetailsView
    </h1>

    <asp:UpdatePanel runat="server">
        <ContentTemplate>
            <asp:UpdateProgress runat="server">
                <ProgressTemplate>
                    Processing...
                </ProgressTemplate>
            </asp:UpdateProgress>
            <asp:EntityDataSource runat="server" ID="eds"
                ContextTypeName="Msts.DataAccess.EFData.PubsEntities"
                OnContextCreating="eds_ContextCreating"
                EntitySetName="jobs"
                EnableFlattening="false"
                EnableDelete="true" EnableInsert="true" EnableUpdate="true"
                AutoPage="true" 
                AutoSort="false" AutoGenerateOrderByClause="true"
                Include="employees">

            </asp:EntityDataSource>
            <asp:DetailsView runat="server" ID="dv"
                DataSourceID="eds"
                DataKeyNames="job_id"
                AllowPaging="true"
                AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateInsertButton="true"
                AutoGenerateRows="false"
                OnDataBound="dv_DataBound"
                OnItemUpdating="dv_ItemUpdating">
                <Fields>
                    <asp:BoundField DataField="job_id" HeaderText="ID" ReadOnly="true" InsertVisible="false" />
                    <asp:BoundField DataField="job_desc" HeaderText="Description" />
                    <asp:BoundField DataField="min_lvl" HeaderText="Minimum" />
                    <asp:BoundField DataField="max_lvl" HeaderText="Maximum" />
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:GridView runat="server" ID="employeesGrid"
                                DataSource='<%# Eval("employees") %>'
                                DataKeyNames="emp_id"
                                AutoGenerateColumns="false" CellPadding="4" ForeColor="#333333" GridLines="None">
                                <AlternatingRowStyle BackColor="White"></AlternatingRowStyle>
                                <Columns>
                                    <asp:TemplateField HeaderText="Full name">
                                        <ItemTemplate>
                                            <div>
                                                <asp:Label ID="Label1" Text='<%# Eval("fname") %>' runat="server" />
                                                <asp:Label ID="Label2" Text='<%# Eval("lname") %>' runat="server" />
                                            </div>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                </Columns>
                                <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White"></FooterStyle>

                                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White"></HeaderStyle>

                                <PagerStyle HorizontalAlign="Center" BackColor="#FFCC66" ForeColor="#333333"></PagerStyle>

                                <RowStyle BackColor="#FFFBD6" ForeColor="#333333"></RowStyle>

                                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy"></SelectedRowStyle>

                                <SortedAscendingCellStyle BackColor="#FDF5AC"></SortedAscendingCellStyle>

                                <SortedAscendingHeaderStyle BackColor="#4D0000"></SortedAscendingHeaderStyle>

                                <SortedDescendingCellStyle BackColor="#FCF6C0"></SortedDescendingCellStyle>

                                <SortedDescendingHeaderStyle BackColor="#820000"></SortedDescendingHeaderStyle>
                            </asp:GridView>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:EntityDataSource runat="server" ID="eds2"
                                ContextTypeName="Msts.DataAccess.EFData.PubsEntities"
                                OnContextCreating="eds_ContextCreating"
                                EntitySetName="employees"
                                AutoPage="false"
                                AutoSort="false" AutoGenerateOrderByClause="false"
                                EnableDelete="false" EnableFlattening="false" EnableInsert="false" EnableUpdate="false">
                            </asp:EntityDataSource>
                            <asp:ListBox runat="server" ID="employeesList"
                                SelectionMode="Multiple"
                                DataSourceID="eds2" DataTextField="fname" DataValueField="emp_id">
                            </asp:ListBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                </Fields>
            </asp:DetailsView>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
