//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msts.Topics.Chapter07___Server_Controls.Lesson01___User_Controls
{


    public partial class DataBoundTemplatedAddressesControl
    {
    }
}
