//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msts.Topics.Chapter07___Server_Controls.Lesson01___User_Controls {
    
    
    public partial class TemplatedAddress1 {
        
        /// <summary>
        /// templatedAddress1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Msts.Topics.Chapter07___Server_Controls.Lesson01___User_Controls.TemplatedAddress templatedAddress1;
    }
}
