// <auto-generated />
namespace ForeignKeys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddingForeignKeyPropertyToProductTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingForeignKeyPropertyToProductTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201308221938402_AddingForeignKeyPropertyToProductTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
