//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msts.Topics.Chapter09___Scripts.Lesson01___MS_AJAX
{


    public partial class CancelingAsyncPost
    {
    }
}
