//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public Configuration()
        {
            this.DropSources = new HashSet<DropSource>();
        }
    
        public System.Guid ConfigurationId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DropSource> DropSources { get; set; }
    }
}
