//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseName
    {
        public DatabaseName()
        {
            this.DatabaseDeployments = new HashSet<DatabaseDeployment>();
        }
    
        public System.Guid DatabaseId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DatabaseDeployment> DatabaseDeployments { get; set; }
    }
}
