//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeploymentMapping
    {
        public DeploymentMapping()
        {
            this.DatabaseDeployments = new HashSet<DatabaseDeployment>();
            this.DeploymentLogs = new HashSet<DeploymentLog>();
            this.FileDeployments = new HashSet<FileDeployment>();
            this.NugetDeployments = new HashSet<NugetDeployment>();
            this.PowerShellModuleDeployments = new HashSet<PowerShellModuleDeployment>();
            this.SsisDeployments = new HashSet<SsisDeployment>();
            this.WebDeployments = new HashSet<WebDeployment>();
            this.ZipDeployments = new HashSet<ZipDeployment>();
        }
    
        public System.Guid DeploymentMappingId { get; set; }
        public string Name { get; set; }
        public System.Guid Product_ProductId { get; set; }
        public System.Guid Environment_EnvironmentId { get; set; }
    
        public virtual ICollection<DatabaseDeployment> DatabaseDeployments { get; set; }
        public virtual ICollection<DeploymentLog> DeploymentLogs { get; set; }
        public virtual Environment Environment { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<FileDeployment> FileDeployments { get; set; }
        public virtual ICollection<NugetDeployment> NugetDeployments { get; set; }
        public virtual ICollection<PowerShellModuleDeployment> PowerShellModuleDeployments { get; set; }
        public virtual ICollection<SsisDeployment> SsisDeployments { get; set; }
        public virtual ICollection<WebDeployment> WebDeployments { get; set; }
        public virtual ICollection<ZipDeployment> ZipDeployments { get; set; }
    }
}
