//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMessage
    {
        public System.Guid LogMessageId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public string MachineName { get; set; }
        public System.Guid LogType_LogTypeId { get; set; }
        public System.Guid DeploymentLog_DeploymentLogId { get; set; }
    
        public virtual DeploymentLog DeploymentLog { get; set; }
        public virtual LogType LogType { get; set; }
    }
}
