//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkResource
    {
        public NetworkResource()
        {
            this.BackupTargets = new HashSet<BackupTarget>();
            this.FileDeployments = new HashSet<FileDeployment>();
            this.SsisDeployments = new HashSet<SsisDeployment>();
            this.WebDeployments = new HashSet<WebDeployment>();
            this.ZipDeployments = new HashSet<ZipDeployment>();
        }
    
        public System.Guid NetworkResourceId { get; set; }
        public string Name { get; set; }
        public string ShareName { get; set; }
        public bool MapNetworkResource { get; set; }
        public bool UseNetworkResourceCredentials { get; set; }
        public string NetworkResourceUserName { get; set; }
        public string NetworkResourcePassword { get; set; }
        public string Description { get; set; }
        public System.Guid Server_ServerId { get; set; }
    
        public virtual ICollection<BackupTarget> BackupTargets { get; set; }
        public virtual ICollection<FileDeployment> FileDeployments { get; set; }
        public virtual Server Server { get; set; }
        public virtual ICollection<SsisDeployment> SsisDeployments { get; set; }
        public virtual ICollection<WebDeployment> WebDeployments { get; set; }
        public virtual ICollection<ZipDeployment> ZipDeployments { get; set; }
    }
}
