//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceControlLocation
    {
        public System.Guid SourceControlLocationId { get; set; }
        public string SourceControlPath { get; set; }
        public System.Guid TeamProject_TeamProjectId { get; set; }
        public System.Guid Product_ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TeamProject TeamProject { get; set; }
    }
}
