//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebArtifact
    {
        public WebArtifact()
        {
            this.WebDeployments = new HashSet<WebDeployment>();
        }
    
        public System.Guid ArtifactId { get; set; }
        public string PackageFileName { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<WebDeployment> WebDeployments { get; set; }
    }
}
