//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSite
    {
        public WebSite()
        {
            this.WebDeployments = new HashSet<WebDeployment>();
        }
    
        public System.Guid WebSiteId { get; set; }
        public string AppPoolName { get; set; }
        public string WebSiteName { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<WebDeployment> WebDeployments { get; set; }
    }
}
