//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipFileArtifact
    {
        public ZipFileArtifact()
        {
            this.ZipDeployments = new HashSet<ZipDeployment>();
        }
    
        public System.Guid ArtifactId { get; set; }
        public string ZipFileName { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ZipDeployment> ZipDeployments { get; set; }
    }
}
