<%@ Page Title="" Language="C#" MasterPageFile="~/Topics/Chapter02 - Master - themes - caching/Lesson01 - MasterPages/ClassicMaster.Master" AutoEventWireup="true" CodeBehind="WorkingWithTheMembershipUserClass.aspx.cs" Inherits="Msts.Topics.Chapter13___Profiles_and_security.Lesson02___Membership.WorkingWithTheMembershipUserClass" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>
        MembershipUser
    </h1>
    <asp:UpdatePanel runat="server">
        <ContentTemplate>
            <asp:UpdateProgress runat="server" DisplayAfter="0">
                <ProgressTemplate>
                    Processing...
                </ProgressTemplate>
            </asp:UpdateProgress>
            <asp:Panel runat="server" GroupingText="Filter">
                <div>
                    Filter by:
                </div>
                <div>
                    <asp:RadioButtonList runat="server" ID="filterType" CausesValidation="false"
                        AutoPostBack="true" 
                        OnSelectedIndexChanged="filterType_SelectedIndexChanged">
                        <asp:ListItem Text="Email" Selected="True" Value="1" />
                        <asp:ListItem Text="Username" Value="2" />
                    </asp:RadioButtonList>
                </div>
                <div>
                    Email
                </div>
                <div>
                    <asp:TextBox runat="server" ID="emailFilter" />
                </div>
                <div>
                    Username
                </div>
                <div>
                    <asp:TextBox runat="server" ID="usernameFilter" Enabled="false" />
                </div>
                <div>
                    <asp:Button Text="Apply Filter" runat="server" ID="applyFilter" OnClick="applyFilter_Click" />
                    <asp:Button Text="Clear Filter" runat="server" ID="clearFilter" OnClick="clearFilter_Click" />
                </div>
            </asp:Panel>
            <asp:GridView runat="server" ID="gv"
                DataKeyNames="UserName"
                ItemType="System.Web.Security.MembershipUser"
                SelectMethod="gv_GetData"
                AllowPaging="true" PageSize="5"
                AutoGenerateColumns="false" 
                AutoGenerateSelectButton="true"
                AutoGenerateDeleteButton="true"
                DeleteMethod="gv_DeleteItem"
                OnPageIndexChanged="gv_PageIndexChanged"
                OnRowDeleted="gv_RowDeleted">
                <Columns>
                    <asp:DynamicField DataField="UserName" />
                    <asp:DynamicField DataField="Email" />
                </Columns>
                <SelectedRowStyle Font-Bold="true" />
            </asp:GridView>

            <hr />

            <div>
                <asp:Button Text="New" runat="server" ID="newUser" OnClick="new_Click" />
            </div>

            <asp:Panel runat="server" GroupingText="New" ID="newPanel" Visible="false">
                <div>
                    <asp:ValidationSummary runat="server" />
                </div>
                <div>
                    Username:
                </div>
                <div>
                    <asp:TextBox runat="server" ID="username" />
                    <asp:RequiredFieldValidator ErrorMessage="Username required" ControlToValidate="username" runat="server" Text="*" />
                </div>
                <div>
                    Email:
                </div>
                <div>
                    <asp:TextBox runat="server" ID="email" TextMode="Email" />
                    <asp:RequiredFieldValidator ErrorMessage="Email required" ControlToValidate="email" runat="server" Text="*" />
                </div>
                <div>
                    Password:
                </div>
                <div>
                    <asp:TextBox runat="server" ID="password" TextMode="Password" />
                    <asp:RequiredFieldValidator ErrorMessage="Password required" ControlToValidate="password" runat="server" Text="*" />
                </div>
                <div>
                    Confirm Password:
                </div>
                <div>
                    <asp:TextBox runat="server" ID="confirmPassword" TextMode="Password" />
                    <asp:RequiredFieldValidator ErrorMessage="Confirm password required" ControlToValidate="confirmPassword" runat="server" Text="*" />
                    <asp:CompareValidator ErrorMessage="Passwords don't match" ControlToValidate="confirmPassword" runat="server" ControlToCompare="password" Operator="Equal" Text="Don't match" />
                </div>
                <div>
                    Question:
                </div>
                <div>
                    <asp:TextBox ID="question" runat="server" />
                    <asp:RequiredFieldValidator ErrorMessage="Question is required" ControlToValidate="question" runat="server" />
                </div>
                <div>
                    Answer:
                </div>
                <div>
                    <asp:TextBox runat="server" ID="answer" />
                    <asp:RequiredFieldValidator ErrorMessage="Answer required" ControlToValidate="answer" runat="server" />
                </div>
                <div>
                    <asp:Button Text="Create user" runat="server" ID="createUser" OnClick="createUser_Click" />
                    <asp:Button Text="Cancel" runat="server" ID="cancelUserCreation" OnClick="cancelUserCreation_Click" CausesValidation="false" />
                </div>
            </asp:Panel>

            <hr />

            <asp:DetailsView runat="server" ID="dv"
                DataKeyNames="UserName"
                ItemType="System.Web.Security.MembershipUser"
                SelectMethod="dv_GetItem"
                AutoGenerateEditButton="true"
                UpdateMethod="dv_UpdateItem"
                OnItemUpdated="dv_ItemUpdated">

            </asp:DetailsView>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
