//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Build
    {
        public Build()
        {
            this.DeploymentLogs = new HashSet<DeploymentLog>();
            this.Mappings = new HashSet<Mapping>();
        }
    
        public System.Guid BuildId { get; set; }
        public string Name { get; set; }
        public System.Guid TeamProject_TeamProjectId { get; set; }
        public System.Guid Product_ProductId { get; set; }
        public bool IsRelease { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TeamProject TeamProject { get; set; }
        public virtual ICollection<DeploymentLog> DeploymentLogs { get; set; }
        public virtual ICollection<Mapping> Mappings { get; set; }
    }
}
