//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseMigration
    {
        public int MigrationId { get; set; }
        public string BuildNumber { get; set; }
        public int ScriptIndex { get; set; }
        public string ScriptName { get; set; }
        public System.DateTime DateExecuted { get; set; }
        public string ExecutedBy { get; set; }
        public int ScriptYear { get; set; }
    }
}
