//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseDeployment
    {
        public System.Guid DeploymentId { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public System.Guid DatabaseServer_DatabaseServerId { get; set; }
        public System.Guid DatabaseName_DatabaseId { get; set; }
        public System.Guid DeploymentMapping_DeploymentMappingId { get; set; }
        public Nullable<System.Guid> DropSource_DropSourceId { get; set; }
        public Nullable<System.Guid> DropSourceNestedPath_ArtifactId { get; set; }
    
        public virtual DatabaseName DatabaseName { get; set; }
        public virtual DatabaseServer DatabaseServer { get; set; }
        public virtual DeploymentMapping DeploymentMapping { get; set; }
        public virtual DropSourceNestedPath DropSourceNestedPath { get; set; }
        public virtual DropSource DropSource { get; set; }
    }
}
