//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeploymentDestination
    {
        public DeploymentDestination()
        {
            this.FileDeployments = new HashSet<FileDeployment>();
            this.SsisDeployments = new HashSet<SsisDeployment>();
            this.WebDeployments = new HashSet<WebDeployment>();
            this.ZipDeployments = new HashSet<ZipDeployment>();
        }
    
        public System.Guid DeploymentDestinationId { get; set; }
        public string Name { get; set; }
        public string DeploymentPath { get; set; }
    
        public virtual ICollection<FileDeployment> FileDeployments { get; set; }
        public virtual ICollection<SsisDeployment> SsisDeployments { get; set; }
        public virtual ICollection<WebDeployment> WebDeployments { get; set; }
        public virtual ICollection<ZipDeployment> ZipDeployments { get; set; }
    }
}
