//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Environment
    {
        public Environment()
        {
            this.DeploymentMappings = new HashSet<DeploymentMapping>();
            this.Qualities = new HashSet<Quality>();
        }
    
        public System.Guid EnvironmentId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DeploymentMapping> DeploymentMappings { get; set; }
        public virtual ICollection<Quality> Qualities { get; set; }
    }
}
