//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public System.Guid FilterId { get; set; }
        public string UserName { get; set; }
        public string FilterName { get; set; }
        public string TeamProject { get; set; }
        public int DisplayType { get; set; }
        public int BuildsPerDefinition { get; set; }
        public string BuildQuality { get; set; }
        public int DeploymentType { get; set; }
        public string RequestedFor { get; set; }
        public int BuildStatus { get; set; }
        public string MaxFinishTime { get; set; }
        public string MinFinishTime { get; set; }
        public int UseFinishTimes { get; set; }
    }
}
