//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogType
    {
        public LogType()
        {
            this.LogMessages = new HashSet<LogMessage>();
        }
    
        public System.Guid LogTypeId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<LogMessage> LogMessages { get; set; }
    }
}
