//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeploymentConfigurationsEntities : DbContext
    {
        public DeploymentConfigurationsEntities()
            : base("name=DeploymentConfigurationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BackupTarget> BackupTargets { get; set; }
        public DbSet<Build> Builds { get; set; }
        public DbSet<Configuration> Configurations { get; set; }
        public DbSet<DatabaseDeployment> DatabaseDeployments { get; set; }
        public DbSet<DatabaseMigration> DatabaseMigrations { get; set; }
        public DbSet<DatabaseName> DatabaseNames { get; set; }
        public DbSet<DatabaseServer> DatabaseServers { get; set; }
        public DbSet<DeploymentDestination> DeploymentDestinations { get; set; }
        public DbSet<DeploymentLog> DeploymentLogs { get; set; }
        public DbSet<DeploymentMapping> DeploymentMappings { get; set; }
        public DbSet<DeploymentStatu> DeploymentStatus { get; set; }
        public DbSet<DropSourceNestedPath> DropSourceNestedPaths { get; set; }
        public DbSet<DropSource> DropSources { get; set; }
        public DbSet<Email> Emails { get; set; }
        public DbSet<Environment> Environments { get; set; }
        public DbSet<FileDeployment> FileDeployments { get; set; }
        public DbSet<Filter> Filters { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<LogMessage> LogMessages { get; set; }
        public DbSet<LogType> LogTypes { get; set; }
        public DbSet<Mapping> Mappings { get; set; }
        public DbSet<NetworkResource> NetworkResources { get; set; }
        public DbSet<NugetDeployment> NugetDeployments { get; set; }
        public DbSet<NugetServer> NugetServers { get; set; }
        public DbSet<PermittedUser> PermittedUsers { get; set; }
        public DbSet<Platform> Platforms { get; set; }
        public DbSet<PowerShellModuleDeployment> PowerShellModuleDeployments { get; set; }
        public DbSet<PowerShellModule> PowerShellModules { get; set; }
        public DbSet<ProductReleas> ProductReleases { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Quality> Qualities { get; set; }
        public DbSet<QualityMapping> QualityMappings { get; set; }
        public DbSet<Release> Releases { get; set; }
        public DbSet<ScriptPath> ScriptPaths { get; set; }
        public DbSet<Server> Servers { get; set; }
        public DbSet<Solution> Solutions { get; set; }
        public DbSet<SourceControlLocation> SourceControlLocations { get; set; }
        public DbSet<SsisArtifact> SsisArtifacts { get; set; }
        public DbSet<SsisDeployment> SsisDeployments { get; set; }
        public DbSet<SsisFolder> SsisFolders { get; set; }
        public DbSet<SsisProject> SsisProjects { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TeamProject> TeamProjects { get; set; }
        public DbSet<WebArtifact> WebArtifacts { get; set; }
        public DbSet<WebDeployment> WebDeployments { get; set; }
        public DbSet<WebSite> WebSites { get; set; }
        public DbSet<WindowsService> WindowsServices { get; set; }
        public DbSet<ZipDeployment> ZipDeployments { get; set; }
        public DbSet<ZipFileArtifact> ZipFileArtifacts { get; set; }
    }
}
