//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NugetServer
    {
        public NugetServer()
        {
            this.NugetDeployments = new HashSet<NugetDeployment>();
        }
    
        public System.Guid NugetServerId { get; set; }
        public string Name { get; set; }
        public string PublishUri { get; set; }
        public string ApiKey { get; set; }
    
        public virtual ICollection<NugetDeployment> NugetDeployments { get; set; }
    }
}
