//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Builds = new HashSet<Build>();
            this.DeploymentMappings = new HashSet<DeploymentMapping>();
            this.ProductReleases = new HashSet<ProductReleas>();
            this.SourceControlLocations = new HashSet<SourceControlLocation>();
        }
    
        public System.Guid ProductId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Build> Builds { get; set; }
        public virtual ICollection<DeploymentMapping> DeploymentMappings { get; set; }
        public virtual ICollection<ProductReleas> ProductReleases { get; set; }
        public virtual ICollection<SourceControlLocation> SourceControlLocations { get; set; }
    }
}
