//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityMapping
    {
        public QualityMapping()
        {
            this.PermittedUsers = new HashSet<PermittedUser>();
            this.Emails = new HashSet<Email>();
        }
    
        public System.Guid QualityMappingId { get; set; }
        public string Name { get; set; }
        public System.Guid Mapping_MappingId { get; set; }
        public System.Guid Quality_QualityId { get; set; }
    
        public virtual Mapping Mapping { get; set; }
        public virtual Quality Quality { get; set; }
        public virtual ICollection<PermittedUser> PermittedUsers { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
    }
}
