//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Release
    {
        public Release()
        {
            this.ProductReleases = new HashSet<ProductReleas>();
        }
    
        public System.Guid ReleaseId { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public int Iteration { get; set; }
        public bool IsOffCycle { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<ProductReleas> ProductReleases { get; set; }
    }
}
