//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SsisDeployment
    {
        public System.Guid DeploymentId { get; set; }
        public bool DropDeploymentFolder { get; set; }
        public bool CleanDeploymentFolderRecursively { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public System.Guid DeploymentResource_NetworkResourceId { get; set; }
        public Nullable<System.Guid> DeploymentDestination_DeploymentDestinationId { get; set; }
        public Nullable<System.Guid> BackupTarget_BackupTargetId { get; set; }
        public System.Guid DeploymentMapping_DeploymentMappingId { get; set; }
        public Nullable<System.Guid> DropSource_DropSourceId { get; set; }
        public Nullable<System.Guid> DropSourceNestedPath_ArtifactId { get; set; }
        public System.Guid SsisProject_SsisProjectId { get; set; }
        public System.Guid SsisFolder_SsisFolderId { get; set; }
        public System.Guid SsisArtifact_SsisArtifactId { get; set; }
        public System.Guid SsisDeploymentServer_ServerId { get; set; }
    
        public virtual BackupTarget BackupTarget { get; set; }
        public virtual DeploymentDestination DeploymentDestination { get; set; }
        public virtual DeploymentMapping DeploymentMapping { get; set; }
        public virtual DropSourceNestedPath DropSourceNestedPath { get; set; }
        public virtual DropSource DropSource { get; set; }
        public virtual NetworkResource NetworkResource { get; set; }
        public virtual Server Server { get; set; }
        public virtual SsisArtifact SsisArtifact { get; set; }
        public virtual SsisFolder SsisFolder { get; set; }
        public virtual SsisProject SsisProject { get; set; }
    }
}
