//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msts.Topics.Chapter08___Debugging_and_Deploying.Lesson01___Debugging
{


    public partial class DebugJavaScript
    {
    }
}
