//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msts.HelloWorldWcfServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloWorldWcfServiceReference.IHelloWorldWcfService")]
    public interface IHelloWorldWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldWcfService/HelloWorldBare", ReplyAction="http://tempuri.org/IHelloWorldWcfService/HelloWorldBareResponse")]
        string HelloWorldBare(string name, System.DateTime birthdayDate);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHelloWorldWcfService/HelloWorldBare", ReplyAction="http://tempuri.org/IHelloWorldWcfService/HelloWorldBareResponse")]
        System.IAsyncResult BeginHelloWorldBare(string name, System.DateTime birthdayDate, System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorldBare(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldWcfService/HelloWorldWr", ReplyAction="http://tempuri.org/IHelloWorldWcfService/HelloWorldWrResponse")]
        string HelloWorldWr(string name, System.DateTime birthdayDate);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHelloWorldWcfService/HelloWorldWr", ReplyAction="http://tempuri.org/IHelloWorldWcfService/HelloWorldWrResponse")]
        System.IAsyncResult BeginHelloWorldWr(string name, System.DateTime birthdayDate, System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorldWr(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldWcfService/HelloWorldRequestWrapped", ReplyAction="http://tempuri.org/IHelloWorldWcfService/HelloWorldRequestWrappedResponse")]
        string HelloWorldRequestWrapped(string name, System.DateTime birthdayDate);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHelloWorldWcfService/HelloWorldRequestWrapped", ReplyAction="http://tempuri.org/IHelloWorldWcfService/HelloWorldRequestWrappedResponse")]
        System.IAsyncResult BeginHelloWorldRequestWrapped(string name, System.DateTime birthdayDate, System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorldRequestWrapped(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldWcfService/HelloWorldResponseWrapped", ReplyAction="http://tempuri.org/IHelloWorldWcfService/HelloWorldResponseWrappedResponse")]
        string HelloWorldResponseWrapped(string name, System.DateTime birthdayDate);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHelloWorldWcfService/HelloWorldResponseWrapped", ReplyAction="http://tempuri.org/IHelloWorldWcfService/HelloWorldResponseWrappedResponse")]
        System.IAsyncResult BeginHelloWorldResponseWrapped(string name, System.DateTime birthdayDate, System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorldResponseWrapped(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloWorldWcfServiceChannel : Msts.HelloWorldWcfServiceReference.IHelloWorldWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldBareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldBareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldWrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldWrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldRequestWrappedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldRequestWrappedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldResponseWrappedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldResponseWrappedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldWcfServiceClient : System.ServiceModel.ClientBase<Msts.HelloWorldWcfServiceReference.IHelloWorldWcfService>, Msts.HelloWorldWcfServiceReference.IHelloWorldWcfService {
        
        private BeginOperationDelegate onBeginHelloWorldBareDelegate;
        
        private EndOperationDelegate onEndHelloWorldBareDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldBareCompletedDelegate;
        
        private BeginOperationDelegate onBeginHelloWorldWrDelegate;
        
        private EndOperationDelegate onEndHelloWorldWrDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldWrCompletedDelegate;
        
        private BeginOperationDelegate onBeginHelloWorldRequestWrappedDelegate;
        
        private EndOperationDelegate onEndHelloWorldRequestWrappedDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldRequestWrappedCompletedDelegate;
        
        private BeginOperationDelegate onBeginHelloWorldResponseWrappedDelegate;
        
        private EndOperationDelegate onEndHelloWorldResponseWrappedDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldResponseWrappedCompletedDelegate;
        
        public HelloWorldWcfServiceClient() {
        }
        
        public HelloWorldWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<HelloWorldBareCompletedEventArgs> HelloWorldBareCompleted;
        
        public event System.EventHandler<HelloWorldWrCompletedEventArgs> HelloWorldWrCompleted;
        
        public event System.EventHandler<HelloWorldRequestWrappedCompletedEventArgs> HelloWorldRequestWrappedCompleted;
        
        public event System.EventHandler<HelloWorldResponseWrappedCompletedEventArgs> HelloWorldResponseWrappedCompleted;
        
        public string HelloWorldBare(string name, System.DateTime birthdayDate) {
            return base.Channel.HelloWorldBare(name, birthdayDate);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHelloWorldBare(string name, System.DateTime birthdayDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorldBare(name, birthdayDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHelloWorldBare(System.IAsyncResult result) {
            return base.Channel.EndHelloWorldBare(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorldBare(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            System.DateTime birthdayDate = ((System.DateTime)(inValues[1]));
            return this.BeginHelloWorldBare(name, birthdayDate, callback, asyncState);
        }
        
        private object[] OnEndHelloWorldBare(System.IAsyncResult result) {
            string retVal = this.EndHelloWorldBare(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldBareCompleted(object state) {
            if ((this.HelloWorldBareCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldBareCompleted(this, new HelloWorldBareCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldBareAsync(string name, System.DateTime birthdayDate) {
            this.HelloWorldBareAsync(name, birthdayDate, null);
        }
        
        public void HelloWorldBareAsync(string name, System.DateTime birthdayDate, object userState) {
            if ((this.onBeginHelloWorldBareDelegate == null)) {
                this.onBeginHelloWorldBareDelegate = new BeginOperationDelegate(this.OnBeginHelloWorldBare);
            }
            if ((this.onEndHelloWorldBareDelegate == null)) {
                this.onEndHelloWorldBareDelegate = new EndOperationDelegate(this.OnEndHelloWorldBare);
            }
            if ((this.onHelloWorldBareCompletedDelegate == null)) {
                this.onHelloWorldBareCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldBareCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldBareDelegate, new object[] {
                        name,
                        birthdayDate}, this.onEndHelloWorldBareDelegate, this.onHelloWorldBareCompletedDelegate, userState);
        }
        
        public string HelloWorldWr(string name, System.DateTime birthdayDate) {
            return base.Channel.HelloWorldWr(name, birthdayDate);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHelloWorldWr(string name, System.DateTime birthdayDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorldWr(name, birthdayDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHelloWorldWr(System.IAsyncResult result) {
            return base.Channel.EndHelloWorldWr(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorldWr(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            System.DateTime birthdayDate = ((System.DateTime)(inValues[1]));
            return this.BeginHelloWorldWr(name, birthdayDate, callback, asyncState);
        }
        
        private object[] OnEndHelloWorldWr(System.IAsyncResult result) {
            string retVal = this.EndHelloWorldWr(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldWrCompleted(object state) {
            if ((this.HelloWorldWrCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldWrCompleted(this, new HelloWorldWrCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldWrAsync(string name, System.DateTime birthdayDate) {
            this.HelloWorldWrAsync(name, birthdayDate, null);
        }
        
        public void HelloWorldWrAsync(string name, System.DateTime birthdayDate, object userState) {
            if ((this.onBeginHelloWorldWrDelegate == null)) {
                this.onBeginHelloWorldWrDelegate = new BeginOperationDelegate(this.OnBeginHelloWorldWr);
            }
            if ((this.onEndHelloWorldWrDelegate == null)) {
                this.onEndHelloWorldWrDelegate = new EndOperationDelegate(this.OnEndHelloWorldWr);
            }
            if ((this.onHelloWorldWrCompletedDelegate == null)) {
                this.onHelloWorldWrCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldWrCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldWrDelegate, new object[] {
                        name,
                        birthdayDate}, this.onEndHelloWorldWrDelegate, this.onHelloWorldWrCompletedDelegate, userState);
        }
        
        public string HelloWorldRequestWrapped(string name, System.DateTime birthdayDate) {
            return base.Channel.HelloWorldRequestWrapped(name, birthdayDate);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHelloWorldRequestWrapped(string name, System.DateTime birthdayDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorldRequestWrapped(name, birthdayDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHelloWorldRequestWrapped(System.IAsyncResult result) {
            return base.Channel.EndHelloWorldRequestWrapped(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorldRequestWrapped(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            System.DateTime birthdayDate = ((System.DateTime)(inValues[1]));
            return this.BeginHelloWorldRequestWrapped(name, birthdayDate, callback, asyncState);
        }
        
        private object[] OnEndHelloWorldRequestWrapped(System.IAsyncResult result) {
            string retVal = this.EndHelloWorldRequestWrapped(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldRequestWrappedCompleted(object state) {
            if ((this.HelloWorldRequestWrappedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldRequestWrappedCompleted(this, new HelloWorldRequestWrappedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldRequestWrappedAsync(string name, System.DateTime birthdayDate) {
            this.HelloWorldRequestWrappedAsync(name, birthdayDate, null);
        }
        
        public void HelloWorldRequestWrappedAsync(string name, System.DateTime birthdayDate, object userState) {
            if ((this.onBeginHelloWorldRequestWrappedDelegate == null)) {
                this.onBeginHelloWorldRequestWrappedDelegate = new BeginOperationDelegate(this.OnBeginHelloWorldRequestWrapped);
            }
            if ((this.onEndHelloWorldRequestWrappedDelegate == null)) {
                this.onEndHelloWorldRequestWrappedDelegate = new EndOperationDelegate(this.OnEndHelloWorldRequestWrapped);
            }
            if ((this.onHelloWorldRequestWrappedCompletedDelegate == null)) {
                this.onHelloWorldRequestWrappedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldRequestWrappedCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldRequestWrappedDelegate, new object[] {
                        name,
                        birthdayDate}, this.onEndHelloWorldRequestWrappedDelegate, this.onHelloWorldRequestWrappedCompletedDelegate, userState);
        }
        
        public string HelloWorldResponseWrapped(string name, System.DateTime birthdayDate) {
            return base.Channel.HelloWorldResponseWrapped(name, birthdayDate);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHelloWorldResponseWrapped(string name, System.DateTime birthdayDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorldResponseWrapped(name, birthdayDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHelloWorldResponseWrapped(System.IAsyncResult result) {
            return base.Channel.EndHelloWorldResponseWrapped(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorldResponseWrapped(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            System.DateTime birthdayDate = ((System.DateTime)(inValues[1]));
            return this.BeginHelloWorldResponseWrapped(name, birthdayDate, callback, asyncState);
        }
        
        private object[] OnEndHelloWorldResponseWrapped(System.IAsyncResult result) {
            string retVal = this.EndHelloWorldResponseWrapped(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldResponseWrappedCompleted(object state) {
            if ((this.HelloWorldResponseWrappedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldResponseWrappedCompleted(this, new HelloWorldResponseWrappedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldResponseWrappedAsync(string name, System.DateTime birthdayDate) {
            this.HelloWorldResponseWrappedAsync(name, birthdayDate, null);
        }
        
        public void HelloWorldResponseWrappedAsync(string name, System.DateTime birthdayDate, object userState) {
            if ((this.onBeginHelloWorldResponseWrappedDelegate == null)) {
                this.onBeginHelloWorldResponseWrappedDelegate = new BeginOperationDelegate(this.OnBeginHelloWorldResponseWrapped);
            }
            if ((this.onEndHelloWorldResponseWrappedDelegate == null)) {
                this.onEndHelloWorldResponseWrappedDelegate = new EndOperationDelegate(this.OnEndHelloWorldResponseWrapped);
            }
            if ((this.onHelloWorldResponseWrappedCompletedDelegate == null)) {
                this.onHelloWorldResponseWrappedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldResponseWrappedCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldResponseWrappedDelegate, new object[] {
                        name,
                        birthdayDate}, this.onEndHelloWorldResponseWrappedDelegate, this.onHelloWorldResponseWrappedCompletedDelegate, userState);
        }
    }
}
