//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msts.Topics.Chapter10___Services_and_Handlers.Lesson01___Handlers
{


    public partial class ImageRetrieverHandlerPage
    {
    }
}
