//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msts.Topics.Chapter02.Lesson01___MasterPages
{


    public partial class OverridingDefaultThemeWithDynamicMasterPages
    {
    }
}
